whois/__init__.py
whois/tld_regexpr.py

I've just add support to .рф queries

added .рф TLD

---

test.py
whois/_1_query.py
whois/_2_parse.py
whois/_3_adjust.py
whois/__init__.py
whois/exceptions.py

Custom Exceptions instead of generic ones

---

README
whois/tld_regexpr.py

Added support for .id domains

---

README

Resolve https://github.com/DannyCork/python-whois/issues/34

Add explanation about `whois` package

---

whois/_3_adjust.py

fixes #65 as pointed out by @jamesduffy

fix indentation

---

test.py
whois/tld_regexpr.py

Added support for .education and .ninja domains with Tests added.
Tested

Add support for the TLDs: .education and .ninja

---

README
test.py
whois/_2_parse.py
whois/__init__.py
whois/tld_regexpr.py

as in is a reserved work "in_" is the cctld value

Adding IN ccTLD

---

README
whois/tld_regexpr.py

Added support .download top-level domain and on the way updated README with list of supported TLDs.

Added support for .download TLD

---

README
test.py
whois/tld_regexpr.py

Added support for .bank domains.

Add support for .bank

---

whois/tld_regexpr.py

add registrant org regex for .com TLD

---

README
test.py
whois/__init__.py
whois/tld_regexpr.py

Added .com.au ccTLD

---

README
test.py
whois/_3_adjust.py
whois/tld_regexpr.py

add feature ua tld domain support #99 
side effect: convert datetime to UTC and remove tzinfo

add ua tld support, normalize datetime

---

README
test.py
whois/tld_regexpr.py

add .by ccLTD support

---

whois/_1_query.py

solution for issue #139 . It downloads whois.exe from Microsoft server on windows

added support for windows

---

README
test.py
whois/_3_adjust.py
whois/tld_regexpr.py

Hi Danny! This is kinda one of my first contributions on the free software world, feel free to leave any feedback.

Added Peru .pe TLD

---

README
test.py
whois/tld_regexpr.py

This PR adds support for `.courses` and `.study` to the package.

Add support for .courses, .study

---

README
test.py
whois/tld_regexpr.py

Added support for .tz

---

test.py

Add some domain :|

---

README.md
test.py
whois/tld_regexpr.py

Hello @DannyCork, 
An [issue on HomeAssistant](https://github.com/home-assistant/core/issues/67337) lead me to create this PR.
Hopefully everything I've done is correct, let me know if there's anything I can do to help it get merged :)
Cheers

Added .sk TLD

---

README.md
test.py
whois/tld_regexpr.py

Fixes: #189
Seems alright to me, please review @DannyCork

Add .dev domain

---

README.md
test.py
whois/tld_regexpr.py

Hello,
I added support for .bzh and .nc TLDs.
These are not well famous, I hope it won't be a problem.

Adding .bzh and .nc TLDs support, tested with bretagne.bzh and congres.nc

---

test.py
whois/tld_regexpr.py

all mentioned tld's in ./issues/174 now added
reworke test.py so you can limit the group of tested items

rework test.py add fix for: issues/174

---

whois/__init__.py

import idna third-party package dependence deleted. & dict return result added in get function.

import idna third-party package dependence deleted

---

test.py
whois/tld_regexpr.py

https://www.iana.org/domains/root/db/radio.html
Thanks!

add tld: radio

---

whois/__init__.py
whois/tld_regexpr.py

.lviv.ua have compatible with .com format.

Added support of .lviv.ua, it has .com format

---

tests/ok-domains.txt
whois/_3_adjust.py
whois/tld_regexpr.py

I am currently adding support for a few more Top Level Domains.

Add support for new Top Level Domains

---

whois/_2_parse.py
whois/__init__.py
whois/tld_regexpr.py

fix the tld one with explicit server
add the new ones:  page, observer, mk, green , africa, mn

add tld's: page, observer, mk, green , africa, mn

---

README.md
whois/_0_init_tld.py
whois/_2_parse.py
whois/__init__.py

QuotaStrings are used to detect whois over quota for a particular whois server
NoneStrings are used to detect Domain not Registered or not existing domains
for those who need it this is now configurable on the fly

add configurable QuotaStrings and NoneStrings

---

whois/_1_query.py
whois/_2_parse.py

tld xyz on mac: solution for multiple iana in result from whois cli on mac
the output has multiple IANA Source lines, this was not expected
all tests run clean

fix issue with tld xyz on mac

---

whois/tld_regexpr.py

add tld ac.ug and com.tm as privateregistry, they reply with no data

tld ac.ug and com.tm reply with no data

---

whois/_3_adjust.py

unfortunately a timezone offset +hh:mm cannot be parsed in 3.6 in later versions it can be used

python 3.6 does not parse : in the timezone offset

---

whois/tld_regexpr.py

the bd tld seems to have no whois servers on the iana website only a web gui

add bangladesh tls as privateReg

---

whois/tld_regexpr.py

fix tld tv: explicitly add a whois server

fix tld tv

---

whois/tld_regexpr.py

./reformat-code.sh
./test2.py -a 2>2 | tee 1

fix format and ru n full test

---

whois/tld_regexpr.py

Change .rw tld to extend .com and add whois.ricta.org.rw as server

Add rw registry server

---

testdata/example.com/output
testdata/example.net/nameservers
testdata/example.net/output
testdata/example.org/input
testdata/example.org/nameservers
testdata/example.org/output
testdata/hello.xyz/input
testdata/hello.xyz/output
testdata/make_testdata.sh
testdata/meta.co.jp/input
testdata/meta.co.jp/nameservers
testdata/meta.co.jp/output
testdata/meta.co.uk/input
testdata/meta.co.uk/nameservers
testdata/meta.co.uk/output
testdata/meta.com.tr/input
testdata/meta.com.tr/output
testdata/meta.com/input
testdata/meta.com/nameservers
testdata/meta.com/output
testdata/meta.jp/nameservers
testdata/meta.jp/output
testdata/meta.kr/nameservers
testdata/meta.kr/output
testdata/xs4all.nl/output
whois/tld_regexpr.py

tld .edu can now have up to 10 nameservers; new testdata

sync from WhoisDomain and new testdata

---

Makefile
testwhl.py
whois/tldDb/tld_regexpr.py

make test will now run all the defined test cases in the 'tld_regexpr.py'
"_test": "some domain"
output goes to file 2 (stderr) and file 1 (stdout) 
both files are already in .gitignore
just running make (aka: make all) will run the complete test suite also on the whl

update make test

---

README.md
docs/Authors.md
docs/Docker.md
docs/Features.md
docs/Updates.md
docs/Usage.md
docs/_config.yml
docs/index.html
docs/whoisdomain-cli.md
reformat-code.sh
whois/cache/redisCache.py
whois/cache/simpleCacheBase.py
whois/main.py
whois/tldDb/finders.py
whois/tldDb/tld_regexpr.py
whois/version.py
whois/whoisCliInterface.py

additional tld's added as detected by whoisdomain's IANA analizer
remove a few obsolete (retracted) tld's

update to whoisdomain 1.20231115.1
