whois/tld_regexpr.py
Added support for #35 - .sh domains. Two samples: root.sh and unix.sh.
=> Added support for .sh domain.

whois/tld_regexpr.py
Fix info domain regexes.
doing 
```python
whois.query('info.info').__dict__
```
on master : 
```python
{'name': 'info.info',
'registrar': '',
'creation_date': None,
'expiration_date': None,
'last_updated': None,
'name_servers': {'ns1.ams1.afilias-nst.info',
'ns1.hkg1.afilias-nst.info',
'ns1.mia1.afilias-nst.info',
'ns1.sea1.afilias-nst.info',
'ns1.yyz1.afilias-nst.info'}}
```
With this PR: 
```python
{'name': 'info.info',
'registrar': 'Afilias',
'creation_date': datetime.datetime(2001, 10, 8, 16, 33, 16),
'expiration_date': datetime.datetime(2018, 10, 8, 16, 33, 16),
'last_updated': None,
'name_servers': {'ns1.ams1.afilias-nst.info',
'ns1.hkg1.afilias-nst.info',
'ns1.mia1.afilias-nst.info',
'ns1.sea1.afilias-nst.info',
'ns1.yyz1.afilias-nst.info'}}
```
=> Fix info domain parsing

whois/_2_parse.py
It seems the whois command return in every case a response containing first a IANA Whois Server result for the tld only and then the specific whois response for the domain.tld.
This quick fix simply split the response to delete the first part of the IANA response, it appears to works
=> QuickFix for #72 and #52

whois/tld_regexpr.py
Quick fix for the Issue #79 
Whois query for domains ".co.uk" with this fix:
DNS query without fix (issue reported):
=> Issue #79: Fix expiration date for domain .co.uk

whois/tld_regexpr.py
This patch adds support for ir ccTLD.
Unfortunately this TLD does not provide "domain creation date" nor "domain status", so I set them to None.
=> Add IR ccTLD

test.py, whois/_3_adjust.py, whois/__init__.py, whois/tld_regexpr.py
This is directly from the patch in https://github.com/DannyCork/python-whois/issues/16
>>> print(whois.query('google.is').__dict__)
{'name': 'google.is', 'registrar': '', 'creation_date': datetime.datetime(2002, 5, 22, 0, 0), 'expiration_date': datetime.datetime(2020, 5, 22, 0, 0), 'last_updated': None, 'status': '', 'name_servers': {'ns2.google.com', 'ns1.google.com'}}
I'm only looking at the status + name_servers, and so haven't looked at the other attributes
=> Add .is - issue #16

test.py, whois/tld_regexpr.py
Added support for .SE, .NU and .FI ccTLDs
```
>>> print(whois.query("google.se").__dict__)
{'name': 'google.se', 'registrar': 'MarkMonitor Inc', 'creation_date': datetime.datetime(2003, 8, 27, 0, 0), 'expiration_date': datetime.datetime(2020, 10, 20, 0, 0), 'last_updated': datetime.datetime(2019, 9, 18, 0, 0), 'status': 'serverDeleteProhibited', 'name_servers': {'ns1.google.com', 'ns3.google.com', 'ns2.google.com', 'ns4.google.com'}}
>>> print(whois.query("google.nu").__dict__)
{'name': 'google.nu', 'registrar': 'MarkMonitor Inc', 'creation_date': datetime.datetime(1999, 6, 7, 0, 0), 'expiration_date': datetime.datetime(2020, 6, 7, 0, 0), 'last_updated': datetime.datetime(2019, 10, 1, 0, 0), 'status': 'ok', 'name_servers': {'ns1.google.com', 'ns3.google.com', …
```
=> Added support for .SE, .NU and .FI TLDs

whois/_3_adjust.py
Some domains have multiple status tags, at least in the .com TLD.
I don't feel comfortable sharing the actual domain that I've run into this issue with, because it's malicious. However the raw whois results look contain this:
```
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Domain Status: clientHold https://icann.org/epp#clientHold
```
This PR adds a property `statuses` that contains an array of all the statuses.
Sample code:
```python
import sys
import whois
from pprint import pprint
domain = whois.query(sys.argv[1])
pprint(domain.statuses)
```
Output:
```python
['clientHold …
```
=> Make all statusses accessible

whois/tld_regexpr.py
Title says it most.
The regex for name servers is a bit nasty. In the code is the best I could come up with. It supports up to 6 entries, which should be enough, right...
One might consider a trick like that for the registrar too. Both records are multi-lined and, unlike most registrars, not prefixed on every line.  
Example:
```python3
domain = whois.query("google.nl")
pprint(domain.__dict__)
{'creation_date': datetime.datetime(1999, 5, 27, 0, 0),
'expiration_date': None,
'last_updated': datetime.datetime(2015, 12, 30, 0, 0),
'name': 'google.nl',
'name_servers': {'ns1.google.com',
'ns2.google.com',
'ns3.google.com',
'ns4.google.com'},
'registrar': 'MarkMonitor Inc.',
'status': 'active',
'statuses': ['active']}
```
From whois:
```
$ whois google.nl
Domain name: google.nl
Status: …
```
=> Add .nl TLD support

whois/tld_regexpr.py
Title says it all, fix missing registrar and expiration date for .pl domains
```
$ whois google.pl
DOMAIN NAME:           google.pl
registrant type:       organization
nameservers:           ns1.google.com.
ns2.google.com.
ns3.google.com.
ns4.google.com.
created:               2002.09.19 13:00:00
last modified:         2019.08.17 11:36:41
renewal date:          2020.09.18 14:00:00
option created:        2017.10.14 09:30:46
option expiration date:       2020.10.14 09:30:46
dnssec:                Unsigned
REGISTRAR:
Markmonitor, Inc.
3540 East Longwing Lane, Suite 300
Meridian, Idaho 83646
United States
+1.2083895740
ccops@markmonitor.com
WHOIS database responses and Registrant data available at: https://dns.pl/en/whois
WHOIS displays data with a delay not exceeding 15 minutes in relation …
```
=> fix missing registrar and expiration date for .pl domains

whois/tld_regexpr.py
I was unable to get results trying to query any .ca domains. After some debugging I found that the regexes set for .ca weren't matching the results I was getting on the command line from `whois`. I've tested a few hundred .ca domains with this change and they seem to populate properly.
I'm on Ubuntu 20.04 using whois 5.5.6.
=> Fix regexes for .ca

whois/tld_regexpr.py
Hi!
This PR adds expiration date parsing for `.fr` domains.
```
$ python3 -c 'import whois; domain = whois.query("facebook.fr"); print(domain.expiration_date)'
2021-05-10 13:47:36
$ python3 -c 'import whois; domain = whois.query("lemonde.fr"); print(domain.expiration_date)'
2021-02-11 04:00:07
```
:sunflower:
=> add expiration date .fr

whois/tld_regexpr.py
Some parts of output were in Japanese.
The output seemed to be consistent with Japanese IP and non-Japanese IP.
Tested with `amazon.co.jp` and `hatenablog.jp`.
=> Fixing regex for .jp and .co.jp

whois/_2_parse.py, whois/_3_adjust.py
**Summary**
As of now, most of WHOIS response should be containing DNSSEC as DNSSEC is one of the most important security mechanism for the DNS protocol.
Because RDAP supports DNSSEC result as per the official specification and most of WHOIS responses return DNSSEC responses, it is highly recommended to add DNSSEC status in the whois module.
I'm using this for my personal project, and it's up to you to merge this request.
**Reference:**
https://manage.whois.com/kb/node/1908
https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions
https://developers.cloudflare.com/registrar/cloudflare-registrar/dnssec/
=> Add DNSSEC Result

whois/_1_query.py
`whois` command has inconsistent parameters between distros.
This resulted an inconsistent output on `.co.jp` and `.jp`.
To resolve this issue, LANG parameter on env was explicitly added to make sure that Japanese NICs always return responses in Japanese.
It is also good to note that LANG parameter is exclusively used for Japanese NICs at the current stage. 😞 
Unix Official Guideline:
https://www.unix.com/man-page/redhat/1/whois/
```
ENVIRONMENT
LANG
When querying whois.nic.ad.jp and whois.jprs.jp English text is requested unless the LANG or LC_MESSAGES environment variables specify a Japanese locale.
```
On Debian:
https://manpages.debian.org/testing/whois/whois.1.en.html
```
ENVIRONMENT
LANG
When querying whois.nic.ad.jp and whois.jprs.jp English text is requested unless the LANG or …
```
=> Force adding LANG environment for reliable output

README, test.py, whois/tld_regexpr.py
I've re-used the regex dict from bank for 3 new domains which is why they're all initialized on the same line, that config seems to be fairly universal.
=> Added domains .ca, .mu and .rw.

whois/tld_regexpr.py
Hi just putting in a pull request for issue: Add .kz #26
I encountered an exception when testing:
Python 3.7.6 (default, Sep 28 2020, 21:47:29) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> whois.query('primeminister.kz')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/mnt/g/Programming/python/dev/python-whois/whois/__init__.py", line 75, in query
return Domain(pd) if pd['domain_name'][0] else None
File "/mnt/g/Programming/python/dev/python-whois/whois/_3_adjust.py", line 14, in __init__
self.registrant_country = data['registrant_country'][0].strip()
KeyError: 'registrant_country'
Added a few keys to KZ in tld_regexpr.py needed by the Domain class.
=> Added required keys for kz domain

README, whois/tld_regexpr.py
Add South African domains.
Domains including .co.za .
=> Add South Africa .za https://www.zadna.org.za

.gitignore, test.py, whois/_1_query.py, whois/_2_parse.py, whois/_3_adjust.py, whois/__init__.py, whois/tld_regexpr.py
PR includes:
- added abuse_contact and reseller optional attributes (.nl TLD)
- extended DNSSEC check for .nl TLD ('yes')
- corrected mistake in Windows process starter (missing '.exe')
- now raises UnknownTld exception instead of terminating at unknown TLD
- various PEP8/code format improvements
TODO:
- version number?
- add abuse contact to more TLDs
=> Correct exception raise for unknown TLD, .nl domain update, PEP8

test.py, whois/tld_regexpr.py
Various TLDs that did not extend .com failed because of the missing yet mandatory `registrant_country`
=> Fixes missing registrant_country leading to KeyErrors, adds .nl to test.py

README, setup.py, test.py, whois/_1_query.py, whois/_3_adjust.py, whois/__init__.py, whois/tld_regexpr.py
Propose to bump to 9.9.10 (Please create tag @DannyCork)
Now ignore decode errors (com.tr on Windows returns non-UTF-8 characters)
When no name servers are defined, now return None instead of 'set()'
Return registrant when defined
Add two missing dateformats
Adds support for:
- .com.tr
- .sale
- .link
- .game
- .trade
- .ink
- .pub
- .am
- .im
- .fm
- .hk
- .cr
- .global
- .co.il
- .in
- .pt
Fixes #138 
Fixes #130
Fixes #128
Fixes #126
Fixes #111 
Fixes #83
Fixes #37
=> Adds new TLDs by request

README, setup.py, whois/__init__.py, whois/tld_regexpr.py
Changes:
- Support for .amsterdam and .frl
- Nameservers now returned for .eu domains
- Support Fully Qualified Domain Names which entails a trailing dot (eg. `google.com.`)
- UnknownTld exception now provides error message
=> Add .frl .amsterdam support, fix .eu NS, support FQDNs

whois/tld_regexpr.py
Before:
>>> import whois; q = whois.query('wctegeltje.nl'); q.__dict__['name_servers']
{'ns1.osso.nl', 'ns2.osso.nl', 'ns3.osso.io'}
>>> import whois; q = whois.query('osso.nl'); q.__dict__['name_servers']
After:
>>> import whois; q = whois.query('wctegeltje.nl'); q.__dict__['name_servers']
{'ns3.osso.io', 'ns2.osso.nl', 'ns1.osso.nl'}
>>> import whois; q = whois.query('osso.nl'); q.__dict__['name_servers']
{'ns3.osso.io', 'ns2.osso.nl', 'ns1.osso.nl'}
Additionally: uses re.VERBOSE (re.X) to explain what we're doing.
Fixes #157
=> Fix nameserver parsing for .nl TLD when glue records are present

.github/ISSUE_TEMPLATE/bug_report.md
Previously I thought all programming languages will identify "Cork"=="cork" like Scratch but of f*** Ruby (the language that GitHub uses) but didn't think about it so it raises error 👎🏻 
So I fix the template file.
=> Fix bug_report.md

whois/_1_query.py, whois/tld_regexpr.py
1. Add support on .ax/.gy TLD
2. `.jp` and its siblings have been updated last week. it made the output inconsistent again due to the `LANG` environment variable changes across systems, hence adding `LANG=en` environment variable on the `whois` command to make sure that output only comes in English and not in Japanese.
=> Support .ax/.gy TLD, make .jp out consistent

whois/tld_regexpr.py
i expect this is actually a problem for more tld's
but for now this fixes all au tld's where Last Modified may be empty string by explicitly not matching \n
=> fix emptry last modified for au domains (fix for #228 )

.gitignore, test2.py, whois/_2_parse.py, whois/__init__.py, whois/tld_regexpr.py
do_parse:
- no functional changes just moving parts of code to their own functions to unclutter do_parse
- this prepares for the later handling of IANA domains like example.com and exmple.net which will introduce changed behaviour
- 
test2:
- changed test2 to show the variable type and highlight empty strings as return value when no data is present
=> move sections in do_parse to functions; prepare for handling old style IANA domain

README.md, test2.py, whois/_2_parse.py
all changes local in do_parse 
handle iana as a special case returning a response with sufficient default values but handling the patterns use by iana
```
test domain: <<<<<<<<<< example.com >>>>>>>>>>>>>>>>>>>>
name               str               'example.com'
tld                str               'com'
registrar          str               ''
registrant_country str               ''
creation_date      datetime.datetime 1992-01-01 00:00:00
expiration_date    NoneType          None
last_updated       NoneType          None
status             str               ''
statuses           list              ['']
dnssec             bool              False
name_servers       list              []
registrant         str               ''
```
=> add support for iana domains

.gitignore, README.md, test.sh, testdata/example.com/input, testdata/example.com/output, testdata/example.net/input, testdata/example.net/output, testdata/example.org/input, testdata/example.org/output, testdata/make_testdata.sh, testdata/meta.co.uk/input, testdata/meta.co.uk/output, whois/_1_query.py, whois/_3_adjust.py
Create static testing data to test against known input and known output.
Data is added to testdata/<domain>/ on running ./testdata/make_testdata.sh.
./test.sh will execute ./test2.py with env TEST_WHOIS_PYTHON set,
this will cause the whois command not to be used, static input data will be used instead so we have a predictable input and a static output against which we will compare the result of test2.py -d <domain>
=> create a test environment with static test data

test2.py, testdata/example.com/output, testdata/example.net/output, testdata/example.org/input, testdata/example.org/output, testdata/make_testdata.sh, testdata/meta.co.uk/input, testdata/meta.co.uk/output, whois/_3_adjust.py, whois/__init__.py
passing the flag include_raw_whois_text=True will add a extra "text" field to Domain and __dict__
the default is False so the default behavior is unchanged
w = whois.query("google.com")
print(w.__dict__)
{'name': 'google.com', 'tld': 'com', 'registrar': 'MarkMonitor, Inc.', 'registrant_country': 'US', 'creation_date': datetime.datetime(1997, 9, 15, 9, 0), 'expiration_date': None, 'last_updated': datetime.datetime(2019, 9, 9, 17, 39, 4), 'status': 'clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)', 'statuses': ['clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)', 'clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)', 'clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)', 'serverDeleteProhibited …
=> add text to Domain result; but only if requested

.gitignore, README.md, makeTestdataAll.sh, test.sh, test2.py, whois/_1_query.py, whois/_3_adjust.py, whois/__init__.py
use the same type of file reading on Popen and the testFile
rename variables in __init__ query: d -> dl, pd -> data, q -> whois_str, so the function args are the same as are all others already
split of the beginning of query into clearly named functions to increase readability of the steps done
=> Refactor and add getting the raw whois data also for unsupported tld's 

test.py, whois/_1_query.py, whois/_2_parse.py, whois/tld_regexpr.py
Suppress \r from response lines
Search whois.exe in all path contained in PATH environment variable
'None' responses may indicate the need to query a different whois server
Set _server to whois.nic.ai, which returns details instead of 'None'
=> Fix for Windows, list of test with 'None' result, server for AI TLD

whois/tld_regexpr.py
My whois requests to .design TLD has no "expiration_date". After check tld regexp, I found a mistake in "ac" regexp, which the .design tld uses.
Normal whois output looks like: 
`Registry Expiry Date: 2025-02-17T23:59:59Z`
=> Fix regexp in ac tld

test3.py, whois/tld_regexpr.py
the output of host -t ns <domain> gives a list of nameservers, if the number of nameservers from dns is different from whois the test program test3.py writes to output so we can see what we possibly have to fix
many domains actually have more nameservers in dns then in whois but for a few we found some fixes in the regex
=> validate nameservers against dns output,  fix discrepancies where possible

whois/_2_parse.py
example is meta.firewall.org fails with Malformed request 
but firewall.org is the valid registered domain
=> add Malformed request to valid None return so that we retry one level up

README.md, makeTestdataAll.sh, test.sh, whois/_1_query.py, whois/__init__.py
If one have a case to use this library in an external tooling (e.g. monitoring solutions), it would be nice to allow changing maximum cache age. Such an option will allow to not reimplement own caches solution in such an external tooling and also reduce default 2 days cache age to provide changed domain info faster.
To do this, introduce additional option `cache_age` in do_query function.
=> Add an opportunity to specify max cache age

whois/_1_query.py, whois/__init__.py, whois/exceptions.py
Note the default timeout of the whois CLI is 61 seconds, which is too long for many applications.
=> Added `timeout` parameter to limit the maximum wait time when running the whois CLI

reformat-code.sh, test2.py, whois/__init__.py
discovered one missing exception on import, test runs ok now
to run a test on all known tld's
./test2.py -a 2>2 | tee 1 
has 30 seconds timeout now
file 2 (the stderr output) should remain empty and all exceptions are reported at the end of the run in file 1
WhoisCommandTimeout meta.com.au 
WhoisCommandTimeout meta.eus 
WhoisCommandTimeout meta.pt
=> testing the new timeout

whois/tld_regexpr.py
```
>>> whois.query("crypto.tv").__dict__
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute '__dict__'
```
=> fix .tv whois server

whois/_1_query.py
whois shell error ignore.
```
>>> whois.query("520gpt.com")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/ubuntu/python-whois/whois/__init__.py", line 279, in query
whois_str = do_query(
File "/home/ubuntu/python-whois/whois/_1_query.py", line 71, in do_query
_do_whois_query(
File "/home/ubuntu/python-whois/whois/_1_query.py", line 198, in _do_whois_query
raise WhoisCommandFailed(r)
whois.exceptions.WhoisCommandFailed: connect: Connection refused
Domain Name: 520GPT.COM
Registry Domain ID: 2756476274_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.gname.com
Registrar URL: http://www.gname.com
Updated Date: 2023-02-06T06:17:39Z
```
=> fix connect: Connection refused

whois/tld_regexpr.py
Add registry for .ke, or.ke, .ac.ke, .co.ke as whois.kenic.or.ke
=> Add .ke registry
